name = "haiku_monument_api"
main = "src/index.ts"
compatibility_date = "2025-01-24"

compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "haiku-monument-db"
database_id = "c86570ec-9fbb-4658-8e98-956ee306616a"
migrations_dir = "src/infrastructure/db/migrations"

# 環境変数: 有料プランの場合は 'paid' に設定
[vars]
WORKERS_PLAN = "free"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1

